---
engines:
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.css"
  - "**.coffee"
  - "**.js"
  - "**.jsx"
exclude_paths:
- node_modules/*
- public/*
