language: node_js
node_js:
  - '4.1'
services:
  - redis-server
before_install:
  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install rethinkdb
  - sudo /etc/init.d/rethinkdb restart
before_script:
  - sudo rethinkdb --daemon

addons:
  code_climate:
    repo_token: d6928984d10fc9add6d886040556726d92ad86a7d1efc4b448be9945962a41f9

after_script:
  - istanbul cover node_modules/mocha/bin/_mocha -- -R spec --timeout 5000
  - codeclimate-test-reporter < coverage/lcov.info
