language: node_js
node_js:
  - '4.1'
services:
  - redis-server
before_install:
  - sudo add-apt-repository ppa:rethinkdb/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install rethinkdb -y
before_script:
  - sudo rethinkdb --daemon
script:
  - npm test
after_script:
  - killall rethinkdb
